"""Tournament routes: listing/search, organiser-only creation, detail, and public share view."""

from __future__ import annotations

from flask import abort, flash, redirect, render_template, request, url_for
from flask_login import current_user, login_required

from ..decorators import require_role
from ..extensions import db
from ..follows.services import followed_ids, is_following
from ..integrations.geocoding import geocode_address
from ..models import (
    FollowTarget,
    Match,
    MatchStatus,
    Team,
    TournamentTeam,
    Tournament,
    TournamentFormat,
    TournamentStatus,
    Venue,
)
from . import bp
from .forms import TournamentCreateForm

_PAGE_SIZE = 9


def _team_short_code(name: str, fallback: str = "TBD") -> str:
    """Derive a 3-4 char uppercase code from a team name for compact display."""
    cleaned = "".join(c for c in name.upper() if c.isalpha())
    return (cleaned[:3] or fallback)[:4]


def _owned_tournament_or_403(tournament_id: int) -> Tournament:
    tournament = db.session.get(Tournament, tournament_id) or abort(404)
    if tournament.organiser_id != current_user.id:
        abort(403)
    return tournament


def _sync_team_count(tournament: Tournament) -> None:
    tournament.team_count = TournamentTeam.query.filter_by(
        tournament_id=tournament.id
    ).count()


@bp.route("")
def list_view():
    q = (request.args.get("q") or "").strip()
    status_arg = (request.args.get("status") or "all").lower()
    page = max(int(request.args.get("page", 1) or 1), 1)

    query = Tournament.query.order_by(Tournament.start_date.desc())
    if q:
        like = f"%{q}%"
        query = query.filter(Tournament.name.ilike(like))
    if status_arg in {"upcoming", "live", "completed"}:
        query = query.filter(Tournament.status == TournamentStatus(status_arg))

    total = query.count()
    tournaments = query.offset((page - 1) * _PAGE_SIZE).limit(_PAGE_SIZE).all()
    pages = max(1, (total + _PAGE_SIZE - 1) // _PAGE_SIZE)

    return render_template(
        "tournaments/list.html",
        tournaments=tournaments,
        q=q,
        status=status_arg,
        page=page,
        pages=pages,
        total=total,
    )


@bp.route("/create", methods=["GET", "POST"])
@login_required
@require_role("organizer")
def create():
    """Create a tournament + its teams (and optional venue) in a single transaction.

    Restricted to users with the ``organizer`` role. The new tournament's
    ``share_slug`` is auto-generated by the model default for anonymous sharing.
    """
    form = TournamentCreateForm()
    available_teams = (
        Team.query.filter_by(organiser_id=current_user.id).order_by(Team.name.asc()).all()
    )
    form.team_ids.choices = [(team.id, team.name) for team in available_teams]

    if form.validate_on_submit():
        selected_ids = list(dict.fromkeys(form.team_ids.data))
        if len(selected_ids) < 2:
            flash("Select at least two existing teams to create a tournament.", "warning")
            return render_template(
                "tournaments/create.html", form=form
            )
        selected_teams = [team for team in available_teams if team.id in selected_ids]
        if len(selected_teams) != len(selected_ids):
            flash("One or more selected teams are no longer available.", "warning")
            return render_template("tournaments/create.html", form=form)

        venue = None
        if form.venue_name.data and form.venue_address.data:
            address = form.venue_address.data.strip()
            # Geocoding is best-effort: returns None without an API key or on failure,
            # leaving lat/lng null so the client falls back to OpenStreetMap.
            coords = geocode_address(address)
            venue = Venue(
                name=form.venue_name.data.strip(),
                address=address,
                lat=coords[0] if coords else None,
                lng=coords[1] if coords else None,
            )
            db.session.add(venue)
            db.session.flush()

        tournament = Tournament(
            name=form.name.data.strip(),
            description=(form.description.data or "").strip() or None,
            format=TournamentFormat(form.format.data),
            status=TournamentStatus.UPCOMING,
            start_date=form.start_date.data,
            team_count=len(selected_teams),
            organiser_id=current_user.id,
            venue_id=venue.id if venue else None,
        )
        db.session.add(tournament)
        db.session.flush()

        for team in selected_teams:
            db.session.add(
                TournamentTeam(
                    tournament_id=tournament.id,
                    team_id=team.id,
                )
            )
        _sync_team_count(tournament)

        db.session.commit()
        flash("Tournament created. Add fixtures next.", "success")
        return redirect(url_for("tournaments.detail", tournament_id=tournament.id))

    return render_template("tournaments/create.html", form=form)


def _ordered_teams(tournament: Tournament) -> list[TournamentTeam]:
    # Standings order: points desc, then NRR desc, then name asc as a stable tiebreaker.
    return sorted(
        tournament.tournament_teams,
        key=lambda t: (-t.points, -float(t.nrr or 0), t.team.name),
    )


def _match_payload(matches: list[Match]) -> list[dict]:
    payload = []
    for m in matches:
        innings = {i.batting_team_id: i for i in m.innings}
        a = innings.get(m.team_a_id)
        b = innings.get(m.team_b_id)
        payload.append(
            {
                "match": m,
                "a_score": f"{a.runs}/{a.wickets}" if a else None,
                "b_score": f"{b.runs}/{b.wickets}" if b else None,
            }
        )
    return payload


@bp.route("/<int:tournament_id>")
def detail(tournament_id: int):
    tournament = db.session.get(Tournament, tournament_id) or abort(404)

    matches = (
        Match.query.filter_by(tournament_id=tournament.id)
        .order_by(Match.scheduled_at)
        .all()
    )
    standings = _ordered_teams(tournament)
    registered_team_ids = {entry.team_id for entry in tournament.tournament_teams}
    available_teams: list[Team] = []
    is_organiser = (
        current_user.is_authenticated and current_user.id == tournament.organiser_id
    )
    if is_organiser:
        query = Team.query.filter_by(organiser_id=current_user.id).order_by(Team.name.asc())
        if registered_team_ids:
            query = query.filter(Team.id.notin_(registered_team_ids))
        available_teams = query.all()

    return render_template(
        "tournaments/detail.html",
        tournament=tournament,
        teams=standings,
        matches=_match_payload(matches),
        available_teams=available_teams,
        is_organiser=is_organiser,
        is_following_tournament=is_following(FollowTarget.TOURNAMENT, tournament.id),
        followed_team_ids=followed_ids(FollowTarget.TEAM),
    )


@bp.route("/<int:tournament_id>/teams/add", methods=["POST"])
@login_required
@require_role("organizer")
def add_team(tournament_id: int):
    tournament = _owned_tournament_or_403(tournament_id)
    team_id = request.form.get("team_id", type=int)
    if not team_id:
        flash("Select a team to add.", "warning")
        return redirect(url_for("tournaments.detail", tournament_id=tournament.id))

    team = Team.query.filter_by(id=team_id, organiser_id=current_user.id).first()
    if team is None:
        flash("Selected team is not available.", "warning")
        return redirect(url_for("tournaments.detail", tournament_id=tournament.id))

    existing = TournamentTeam.query.filter_by(
        tournament_id=tournament.id, team_id=team.id
    ).first()
    if existing is not None:
        flash("That team is already part of this tournament.", "warning")
        return redirect(url_for("tournaments.detail", tournament_id=tournament.id))

    db.session.add(TournamentTeam(tournament_id=tournament.id, team_id=team.id))
    db.session.flush()
    _sync_team_count(tournament)
    db.session.commit()
    flash("Team added to tournament.", "success")
    return redirect(url_for("tournaments.detail", tournament_id=tournament.id))


@bp.route("/<int:tournament_id>/teams/<int:team_id>/remove", methods=["POST"])
@login_required
@require_role("organizer")
def remove_team(tournament_id: int, team_id: int):
    tournament = _owned_tournament_or_403(tournament_id)
    entry = TournamentTeam.query.filter_by(
        tournament_id=tournament.id, team_id=team_id
    ).first() or abort(404)

    has_fixtures = (
        Match.query.filter(
            Match.tournament_id == tournament.id,
            (Match.team_a_id == team_id) | (Match.team_b_id == team_id),
        ).first()
        is not None
    )
    if has_fixtures:
        flash(
            "You cannot remove a team after fixtures have been scheduled for it.",
            "warning",
        )
        return redirect(url_for("tournaments.detail", tournament_id=tournament.id))

    db.session.delete(entry)
    db.session.flush()
    _sync_team_count(tournament)
    db.session.commit()
    flash("Team removed from tournament.", "success")
    return redirect(url_for("tournaments.detail", tournament_id=tournament.id))


@bp.route("/<slug>/share")
def public(slug: str):
    """Anonymous-friendly tournament view keyed by the unguessable ``share_slug``.

    No login required; the template uses a trimmed nav so the page stays usable
    for unauthenticated visitors.
    """
    tournament = Tournament.query.filter_by(share_slug=slug).first() or abort(404)
    standings = _ordered_teams(tournament)
    recent = (
        Match.query.filter_by(tournament_id=tournament.id, status=MatchStatus.COMPLETED)
        .order_by(Match.scheduled_at.desc())
        .limit(5)
        .all()
    )
    return render_template(
        "tournaments/public.html",
        tournament=tournament,
        teams=standings,
        recent=_match_payload(recent),
    )
