"""add follows table

Revision ID: 12128c51cf58
Revises: 81e7747a2db2
Create Date: 2026-05-01 12:50:31.161059

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12128c51cf58'
down_revision = '81e7747a2db2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('follows',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('target_type', sa.Enum('tournament', 'team', 'player', name='followtarget'), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'target_type', 'target_id', name='uq_follow_user_target')
    )
    with op.batch_alter_table('follows', schema=None) as batch_op:
        batch_op.create_index('ix_follows_target', ['target_type', 'target_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_follows_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('follows', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_follows_user_id'))
        batch_op.drop_index('ix_follows_target')

    op.drop_table('follows')
    # ### end Alembic commands ###
