"""initial schema: users, tournaments, teams, players, venues, matches, innings, batting/bowling entries, comments

Revision ID: 81e7747a2db2
Revises: 
Create Date: 2026-04-20 10:27:02.511385

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '81e7747a2db2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('display_name', sa.String(length=80), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('organizer', 'user', name='role'), nullable=False),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('avatar_url', sa.String(length=255), nullable=True),
    sa.Column('location', sa.String(length=120), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('venues',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=False),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lng', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tournaments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('format', sa.Enum('round_robin', 'knockout', 'group_stage', name='tournamentformat'), nullable=False),
    sa.Column('status', sa.Enum('upcoming', 'live', 'completed', name='tournamentstatus'), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('team_count', sa.Integer(), nullable=False),
    sa.Column('organiser_id', sa.Integer(), nullable=False),
    sa.Column('venue_id', sa.Integer(), nullable=True),
    sa.Column('share_slug', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['organiser_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['venue_id'], ['venues.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tournaments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tournaments_organiser_id'), ['organiser_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tournaments_share_slug'), ['share_slug'], unique=True)
        batch_op.create_index(batch_op.f('ix_tournaments_status'), ['status'], unique=False)

    op.create_table('teams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tournament_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('short_code', sa.String(length=4), nullable=False),
    sa.Column('played', sa.Integer(), nullable=False),
    sa.Column('won', sa.Integer(), nullable=False),
    sa.Column('lost', sa.Integer(), nullable=False),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.Column('nrr', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['tournament_id'], ['tournaments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('teams', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_teams_tournament_id'), ['tournament_id'], unique=False)

    op.create_table('matches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tournament_id', sa.Integer(), nullable=False),
    sa.Column('venue_id', sa.Integer(), nullable=True),
    sa.Column('team_a_id', sa.Integer(), nullable=False),
    sa.Column('team_b_id', sa.Integer(), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(), nullable=False),
    sa.Column('status', sa.Enum('upcoming', 'live', 'completed', name='matchstatus'), nullable=False),
    sa.Column('toss_winner_id', sa.Integer(), nullable=True),
    sa.Column('toss_decision', sa.Enum('bat', 'bowl', name='tossdecision'), nullable=True),
    sa.Column('winner_id', sa.Integer(), nullable=True),
    sa.Column('result_text', sa.String(length=160), nullable=True),
    sa.Column('external_id', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['team_a_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['team_b_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['toss_winner_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['tournament_id'], ['tournaments.id'], ),
    sa.ForeignKeyConstraint(['venue_id'], ['venues.id'], ),
    sa.ForeignKeyConstraint(['winner_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('matches', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_matches_tournament_id'), ['tournament_id'], unique=False)
        batch_op.create_index('ix_matches_tournament_scheduled', ['tournament_id', 'scheduled_at'], unique=False)

    op.create_table('players',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('role', sa.Enum('batter', 'bowler', 'all_rounder', 'wicket_keeper', name='playerrole'), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=True),
    sa.Column('tournament_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('body', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('(match_id IS NOT NULL) <> (tournament_id IS NOT NULL)', name='ck_comment_target_xor'),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ),
    sa.ForeignKeyConstraint(['tournament_id'], ['tournaments.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_comments_match_id'), ['match_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_comments_tournament_id'), ['tournament_id'], unique=False)

    op.create_table('innings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('inning_number', sa.Integer(), nullable=False),
    sa.Column('batting_team_id', sa.Integer(), nullable=False),
    sa.Column('bowling_team_id', sa.Integer(), nullable=False),
    sa.Column('runs', sa.Integer(), nullable=False),
    sa.Column('wickets', sa.Integer(), nullable=False),
    sa.Column('overs', sa.Numeric(precision=4, scale=1), nullable=False),
    sa.ForeignKeyConstraint(['batting_team_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['bowling_team_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('innings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_innings_match_id'), ['match_id'], unique=False)

    op.create_table('batting_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('innings_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('runs', sa.Integer(), nullable=False),
    sa.Column('balls', sa.Integer(), nullable=False),
    sa.Column('fours', sa.Integer(), nullable=False),
    sa.Column('sixes', sa.Integer(), nullable=False),
    sa.Column('dismissal', sa.String(length=160), nullable=True),
    sa.Column('is_not_out', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['innings_id'], ['innings.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('batting_entries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_batting_entries_innings_id'), ['innings_id'], unique=False)

    op.create_table('bowling_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('innings_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('overs', sa.Numeric(precision=4, scale=1), nullable=False),
    sa.Column('maidens', sa.Integer(), nullable=False),
    sa.Column('runs', sa.Integer(), nullable=False),
    sa.Column('wickets', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['innings_id'], ['innings.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('bowling_entries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bowling_entries_innings_id'), ['innings_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bowling_entries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bowling_entries_innings_id'))

    op.drop_table('bowling_entries')
    with op.batch_alter_table('batting_entries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_batting_entries_innings_id'))

    op.drop_table('batting_entries')
    with op.batch_alter_table('innings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_innings_match_id'))

    op.drop_table('innings')
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_comments_tournament_id'))
        batch_op.drop_index(batch_op.f('ix_comments_match_id'))

    op.drop_table('comments')
    op.drop_table('players')
    with op.batch_alter_table('matches', schema=None) as batch_op:
        batch_op.drop_index('ix_matches_tournament_scheduled')
        batch_op.drop_index(batch_op.f('ix_matches_tournament_id'))

    op.drop_table('matches')
    with op.batch_alter_table('teams', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_teams_tournament_id'))

    op.drop_table('teams')
    with op.batch_alter_table('tournaments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tournaments_status'))
        batch_op.drop_index(batch_op.f('ix_tournaments_share_slug'))
        batch_op.drop_index(batch_op.f('ix_tournaments_organiser_id'))

    op.drop_table('tournaments')
    op.drop_table('venues')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    # ### end Alembic commands ###
