"""Static demo data consumed by ``flask seed``."""

from __future__ import annotations

from datetime import UTC, date, datetime

from .models import (
    MatchStatus,
    PlayerRole,
    Role,
    TossDecision,
    TournamentFormat,
    TournamentStatus,
)

SEED_USERS = [
    {
        "key": "cheng",
        "email": "cheng@example.com",
        "display_name": "Cheng Zhang",
        "role": Role.ORGANIZER,
        "bio": "Club cricketer from Perth. Organiser of the UWA Social League.",
        "location": "Perth, WA",
        "password": "password123",
    },
    {
        "key": "priya",
        "email": "priya@example.com",
        "display_name": "Priya Menon",
        "role": Role.USER,
        "bio": "Fan of short-format cricket. Follows local WA leagues.",
        "location": "Perth, WA",
        "password": "password123",
    },
    {
        "key": "daniel",
        "email": "daniel@example.com",
        "display_name": "Daniel Park",
        "role": Role.USER,
        "bio": "Off-spinner.",
        "location": "Perth, WA",
        "password": "password123",
    },
]

SEED_VENUES = {
    "uwa_sports_park": {
        "name": "UWA Sports Park",
        "address": "Hackett Dr, Crawley WA 6009, Australia",
        "lat": -31.9833,
        "lng": 115.8167,
    },
    "fremantle": {
        "name": "Fremantle Community Bank Oval",
        "address": "Parry St, Fremantle WA 6160, Australia",
        "lat": -32.0569,
        "lng": 115.7477,
    },
    "cottesloe": {
        "name": "Cottesloe Beach Reserve",
        "address": "Marine Parade, Cottesloe WA 6011, Australia",
        "lat": -31.9942,
        "lng": 115.7518,
    },
    "nedlands": {
        "name": "Charles Court Reserve",
        "address": "Brockway Rd, Mount Claremont WA 6010, Australia",
        "lat": -31.9630,
        "lng": 115.7779,
    },
    "swan_valley": {
        "name": "Lilac Hill Park",
        "address": "Caversham WA 6055, Australia",
        "lat": -31.8693,
        "lng": 115.9737,
    },
    "midland": {
        "name": "Harold Rossiter Park",
        "address": "14 Robinson Rd, Middle Swan WA 6056, Australia",
        "lat": -31.8879,
        "lng": 116.0034,
    },
}

SEED_TOURNAMENTS = [
    {
        "key": "uwa_social_league_2026",
        "name": "UWA Social League 2026",
        "description": "Friendly weekly 20-over matches between UWA clubs.",
        "format": TournamentFormat.ROUND_ROBIN,
        "status": TournamentStatus.LIVE,
        "start_date": date(2026, 3, 15),
        "team_count": 6,
        "venue_key": "uwa_sports_park",
        "teams": [
            {
                "name": "Crawley Crusaders",
                "short_code": "CRU",
                "played": 5,
                "won": 5,
                "lost": 0,
                "points": 10,
                "nrr": 2.15,
            },
            {
                "name": "Nedlands Knights",
                "short_code": "NED",
                "played": 5,
                "won": 3,
                "lost": 2,
                "points": 6,
                "nrr": 0.82,
            },
            {
                "name": "Claremont Comets",
                "short_code": "CLA",
                "played": 5,
                "won": 3,
                "lost": 2,
                "points": 6,
                "nrr": 0.41,
            },
            {
                "name": "Shenton Sharks",
                "short_code": "SHE",
                "played": 5,
                "won": 2,
                "lost": 3,
                "points": 4,
                "nrr": -0.30,
            },
            {
                "name": "Fremantle Falcons",
                "short_code": "FRE",
                "played": 5,
                "won": 1,
                "lost": 4,
                "points": 2,
                "nrr": -1.25,
            },
            {
                "name": "Perth Panthers",
                "short_code": "PER",
                "played": 5,
                "won": 1,
                "lost": 4,
                "points": 2,
                "nrr": -1.84,
            },
        ],
        "rosters": {
            "Crawley Crusaders": [
                {"name": "Aarav Patel", "role": PlayerRole.BATTER},
                {"name": "James Butler", "role": PlayerRole.ALL_ROUNDER},
                {"name": "Ethan Wu", "role": PlayerRole.BATTER},
                {"name": "Noah Smith", "role": PlayerRole.ALL_ROUNDER},
                {"name": "Jacob Lim", "role": PlayerRole.BOWLER},
                {"name": "Arjun Rao", "role": PlayerRole.ALL_ROUNDER},
                {"name": "Daniel Park", "role": PlayerRole.WICKET_KEEPER},
            ],
            "Nedlands Knights": [
                {"name": "Liam O'Connor", "role": PlayerRole.BATTER},
                {"name": "Ravi Singh", "role": PlayerRole.ALL_ROUNDER},
                {"name": "Sachin Rao", "role": PlayerRole.BOWLER},
                {"name": "Ben Cooper", "role": PlayerRole.BATTER},
                {"name": "Matt Hayes", "role": PlayerRole.BOWLER},
                {"name": "Imran Khan", "role": PlayerRole.BOWLER},
            ],
            "Claremont Comets": [
                {"name": "Oliver Green", "role": PlayerRole.BATTER},
                {"name": "Kieran Moss", "role": PlayerRole.ALL_ROUNDER},
                {"name": "Ryan D'Souza", "role": PlayerRole.BATTER},
                {"name": "Joel Mercer", "role": PlayerRole.WICKET_KEEPER},
                {"name": "Toby Hart", "role": PlayerRole.BOWLER},
                {"name": "Zaid Ali", "role": PlayerRole.ALL_ROUNDER},
            ],
            "Shenton Sharks": [
                {"name": "Haris Malik", "role": PlayerRole.BATTER},
                {"name": "Cooper James", "role": PlayerRole.WICKET_KEEPER},
                {"name": "Dylan Fraser", "role": PlayerRole.ALL_ROUNDER},
                {"name": "Yusuf Patel", "role": PlayerRole.BOWLER},
                {"name": "Sam Nguyen", "role": PlayerRole.ALL_ROUNDER},
                {"name": "Luke Perry", "role": PlayerRole.BOWLER},
            ],
            "Fremantle Falcons": [
                {"name": "Mason Reed", "role": PlayerRole.BATTER},
                {"name": "Callum Price", "role": PlayerRole.ALL_ROUNDER},
                {"name": "Finn Walker", "role": PlayerRole.WICKET_KEEPER},
                {"name": "Zane Brooks", "role": PlayerRole.BATTER},
                {"name": "Aiden Ross", "role": PlayerRole.BOWLER},
                {"name": "Vikram Das", "role": PlayerRole.ALL_ROUNDER},
            ],
            "Perth Panthers": [
                {"name": "Isaac Turner", "role": PlayerRole.BATTER},
                {"name": "Joel Francis", "role": PlayerRole.WICKET_KEEPER},
                {"name": "Kabir Mehta", "role": PlayerRole.ALL_ROUNDER},
                {"name": "Tyler Young", "role": PlayerRole.BATTER},
                {"name": "Hamish Cole", "role": PlayerRole.BOWLER},
                {"name": "Pranav Iyer", "role": PlayerRole.ALL_ROUNDER},
            ],
        },
        "matches": [
            {
                "key": "uwa-match-501",
                "team_a": "Crawley Crusaders",
                "team_b": "Nedlands Knights",
                "scheduled_at": datetime(2026, 4, 12, 14, 0),
                "status": MatchStatus.COMPLETED,
                "winner": "Crawley Crusaders",
                "result_text": "Crawley Crusaders won by 17 runs",
                "innings": [
                    {
                        "batting_team": "Crawley Crusaders",
                        "bowling_team": "Nedlands Knights",
                        "runs": 182,
                        "wickets": 6,
                        "overs": 20.0,
                        "batting": [
                            {
                                "player_name": "Aarav Patel",
                                "runs": 78,
                                "balls": 52,
                                "fours": 8,
                                "sixes": 3,
                                "dismissal": "c Rao b Khan",
                                "is_not_out": False,
                            },
                            {
                                "player_name": "James Butler",
                                "runs": 45,
                                "balls": 38,
                                "fours": 5,
                                "sixes": 1,
                                "dismissal": "b Khan",
                                "is_not_out": False,
                            },
                            {
                                "player_name": "Ethan Wu",
                                "runs": 22,
                                "balls": 18,
                                "fours": 2,
                                "sixes": 0,
                                "dismissal": "run out",
                                "is_not_out": False,
                            },
                            {
                                "player_name": "Noah Smith",
                                "runs": 14,
                                "balls": 9,
                                "fours": 1,
                                "sixes": 1,
                                "dismissal": "c & b Singh",
                                "is_not_out": False,
                            },
                            {
                                "player_name": "Jacob Lim",
                                "runs": 12,
                                "balls": 8,
                                "fours": 1,
                                "sixes": 0,
                                "dismissal": "not out",
                                "is_not_out": True,
                            },
                            {
                                "player_name": "Arjun Rao",
                                "runs": 4,
                                "balls": 5,
                                "fours": 0,
                                "sixes": 0,
                                "dismissal": "b Khan",
                                "is_not_out": False,
                            },
                            {
                                "player_name": "Daniel Park",
                                "runs": 2,
                                "balls": 2,
                                "fours": 0,
                                "sixes": 0,
                                "dismissal": "not out",
                                "is_not_out": True,
                            },
                        ],
                        "bowling": [
                            {
                                "player_name": "Imran Khan",
                                "overs": 4.0,
                                "maidens": 0,
                                "runs": 28,
                                "wickets": 3,
                            },
                            {
                                "player_name": "Ravi Singh",
                                "overs": 4.0,
                                "maidens": 0,
                                "runs": 34,
                                "wickets": 1,
                            },
                            {
                                "player_name": "Sachin Rao",
                                "overs": 4.0,
                                "maidens": 0,
                                "runs": 41,
                                "wickets": 0,
                            },
                            {
                                "player_name": "Ben Cooper",
                                "overs": 4.0,
                                "maidens": 0,
                                "runs": 39,
                                "wickets": 1,
                            },
                            {
                                "player_name": "Matt Hayes",
                                "overs": 4.0,
                                "maidens": 0,
                                "runs": 40,
                                "wickets": 0,
                            },
                        ],
                    },
                    {
                        "batting_team": "Nedlands Knights",
                        "bowling_team": "Crawley Crusaders",
                        "runs": 165,
                        "wickets": 9,
                        "overs": 20.0,
                        "batting": [
                            {
                                "player_name": "Liam O'Connor",
                                "runs": 62,
                                "balls": 44,
                                "fours": 6,
                                "sixes": 2,
                                "dismissal": "c Butler b Park",
                                "is_not_out": False,
                            },
                            {
                                "player_name": "Ravi Singh",
                                "runs": 33,
                                "balls": 28,
                                "fours": 3,
                                "sixes": 1,
                                "dismissal": "b Lim",
                                "is_not_out": False,
                            },
                            {
                                "player_name": "Sachin Rao",
                                "runs": 21,
                                "balls": 20,
                                "fours": 2,
                                "sixes": 0,
                                "dismissal": "c Wu b Butler",
                                "is_not_out": False,
                            },
                            {
                                "player_name": "Ben Cooper",
                                "runs": 18,
                                "balls": 14,
                                "fours": 1,
                                "sixes": 1,
                                "dismissal": "lbw b Lim",
                                "is_not_out": False,
                            },
                            {
                                "player_name": "Matt Hayes",
                                "runs": 10,
                                "balls": 11,
                                "fours": 1,
                                "sixes": 0,
                                "dismissal": "c Smith b Butler",
                                "is_not_out": False,
                            },
                            {
                                "player_name": "Imran Khan",
                                "runs": 9,
                                "balls": 8,
                                "fours": 0,
                                "sixes": 0,
                                "dismissal": "not out",
                                "is_not_out": True,
                            },
                        ],
                        "bowling": [
                            {
                                "player_name": "Daniel Park",
                                "overs": 4.0,
                                "maidens": 0,
                                "runs": 29,
                                "wickets": 2,
                            },
                            {
                                "player_name": "Jacob Lim",
                                "overs": 4.0,
                                "maidens": 1,
                                "runs": 22,
                                "wickets": 3,
                            },
                            {
                                "player_name": "James Butler",
                                "overs": 4.0,
                                "maidens": 0,
                                "runs": 34,
                                "wickets": 2,
                            },
                            {
                                "player_name": "Arjun Rao",
                                "overs": 4.0,
                                "maidens": 0,
                                "runs": 38,
                                "wickets": 1,
                            },
                            {
                                "player_name": "Noah Smith",
                                "overs": 4.0,
                                "maidens": 0,
                                "runs": 42,
                                "wickets": 1,
                            },
                        ],
                    },
                ],
            },
            {
                "key": "uwa-match-502",
                "team_a": "Claremont Comets",
                "team_b": "Shenton Sharks",
                "scheduled_at": datetime(2026, 4, 14, 18, 30),
                "status": MatchStatus.COMPLETED,
                "winner": "Shenton Sharks",
                "result_text": "Shenton Sharks won by 6 wickets",
                "innings": [
                    {
                        "batting_team": "Claremont Comets",
                        "bowling_team": "Shenton Sharks",
                        "runs": 145,
                        "wickets": 7,
                        "overs": 20.0,
                        "batting": [
                            {
                                "player_name": "Oliver Green",
                                "runs": 41,
                                "balls": 31,
                                "fours": 5,
                                "sixes": 1,
                                "dismissal": "c James b Perry",
                                "is_not_out": False,
                            },
                            {
                                "player_name": "Kieran Moss",
                                "runs": 29,
                                "balls": 24,
                                "fours": 2,
                                "sixes": 1,
                                "dismissal": "lbw b Patel",
                                "is_not_out": False,
                            },
                            {
                                "player_name": "Ryan D'Souza",
                                "runs": 24,
                                "balls": 22,
                                "fours": 3,
                                "sixes": 0,
                                "dismissal": "b Nguyen",
                                "is_not_out": False,
                            },
                            {
                                "player_name": "Joel Mercer",
                                "runs": 18,
                                "balls": 16,
                                "fours": 1,
                                "sixes": 0,
                                "dismissal": "c Malik b Fraser",
                                "is_not_out": False,
                            },
                            {
                                "player_name": "Toby Hart",
                                "runs": 14,
                                "balls": 10,
                                "fours": 1,
                                "sixes": 0,
                                "dismissal": "run out",
                                "is_not_out": False,
                            },
                            {
                                "player_name": "Zaid Ali",
                                "runs": 11,
                                "balls": 9,
                                "fours": 1,
                                "sixes": 0,
                                "dismissal": "not out",
                                "is_not_out": True,
                            },
                        ],
                        "bowling": [
                            {
                                "player_name": "Luke Perry",
                                "overs": 4.0,
                                "maidens": 0,
                                "runs": 25,
                                "wickets": 1,
                            },
                            {
                                "player_name": "Yusuf Patel",
                                "overs": 4.0,
                                "maidens": 0,
                                "runs": 30,
                                "wickets": 1,
                            },
                            {
                                "player_name": "Sam Nguyen",
                                "overs": 4.0,
                                "maidens": 0,
                                "runs": 27,
                                "wickets": 1,
                            },
                            {
                                "player_name": "Dylan Fraser",
                                "overs": 4.0,
                                "maidens": 0,
                                "runs": 31,
                                "wickets": 1,
                            },
                            {
                                "player_name": "Haris Malik",
                                "overs": 4.0,
                                "maidens": 0,
                                "runs": 29,
                                "wickets": 0,
                            },
                        ],
                    },
                    {
                        "batting_team": "Shenton Sharks",
                        "bowling_team": "Claremont Comets",
                        "runs": 147,
                        "wickets": 4,
                        "overs": 19.2,
                        "batting": [
                            {
                                "player_name": "Haris Malik",
                                "runs": 52,
                                "balls": 38,
                                "fours": 6,
                                "sixes": 1,
                                "dismissal": "c Mercer b Hart",
                                "is_not_out": False,
                            },
                            {
                                "player_name": "Cooper James",
                                "runs": 27,
                                "balls": 20,
                                "fours": 3,
                                "sixes": 0,
                                "dismissal": "b Ali",
                                "is_not_out": False,
                            },
                            {
                                "player_name": "Dylan Fraser",
                                "runs": 34,
                                "balls": 24,
                                "fours": 2,
                                "sixes": 2,
                                "dismissal": "c Green b Moss",
                                "is_not_out": False,
                            },
                            {
                                "player_name": "Sam Nguyen",
                                "runs": 19,
                                "balls": 15,
                                "fours": 2,
                                "sixes": 0,
                                "dismissal": "not out",
                                "is_not_out": True,
                            },
                            {
                                "player_name": "Yusuf Patel",
                                "runs": 8,
                                "balls": 6,
                                "fours": 1,
                                "sixes": 0,
                                "dismissal": "not out",
                                "is_not_out": True,
                            },
                        ],
                        "bowling": [
                            {
                                "player_name": "Toby Hart",
                                "overs": 4.0,
                                "maidens": 0,
                                "runs": 28,
                                "wickets": 1,
                            },
                            {
                                "player_name": "Zaid Ali",
                                "overs": 4.0,
                                "maidens": 0,
                                "runs": 26,
                                "wickets": 1,
                            },
                            {
                                "player_name": "Kieran Moss",
                                "overs": 4.0,
                                "maidens": 0,
                                "runs": 32,
                                "wickets": 1,
                            },
                            {
                                "player_name": "Oliver Green",
                                "overs": 3.2,
                                "maidens": 0,
                                "runs": 24,
                                "wickets": 0,
                            },
                            {
                                "player_name": "Ryan D'Souza",
                                "overs": 4.0,
                                "maidens": 0,
                                "runs": 35,
                                "wickets": 0,
                            },
                        ],
                    },
                ],
            },
            {
                "key": "uwa-match-503",
                "team_a": "Fremantle Falcons",
                "team_b": "Perth Panthers",
                "scheduled_at": datetime(2026, 4, 17, 14, 0),
                "status": MatchStatus.COMPLETED,
                "winner": "Perth Panthers",
                "result_text": "Perth Panthers won by 5 wickets",
                "innings": [
                    {
                        "batting_team": "Fremantle Falcons",
                        "bowling_team": "Perth Panthers",
                        "runs": 163,
                        "wickets": 8,
                        "overs": 20.0,
                        "batting": [
                            {
                                "player_name": "Mason Reed",
                                "runs": 36,
                                "balls": 29,
                                "fours": 4,
                                "sixes": 1,
                                "dismissal": "c Francis b Cole",
                                "is_not_out": False,
                            },
                            {
                                "player_name": "Callum Price",
                                "runs": 44,
                                "balls": 33,
                                "fours": 3,
                                "sixes": 2,
                                "dismissal": "b Iyer",
                                "is_not_out": False,
                            },
                            {
                                "player_name": "Finn Walker",
                                "runs": 21,
                                "balls": 18,
                                "fours": 2,
                                "sixes": 0,
                                "dismissal": "c Turner b Mehta",
                                "is_not_out": False,
                            },
                            {
                                "player_name": "Zane Brooks",
                                "runs": 28,
                                "balls": 19,
                                "fours": 2,
                                "sixes": 1,
                                "dismissal": "run out",
                                "is_not_out": False,
                            },
                            {
                                "player_name": "Vikram Das",
                                "runs": 17,
                                "balls": 11,
                                "fours": 1,
                                "sixes": 1,
                                "dismissal": "not out",
                                "is_not_out": True,
                            },
                        ],
                        "bowling": [
                            {
                                "player_name": "Hamish Cole",
                                "overs": 4.0,
                                "maidens": 0,
                                "runs": 27,
                                "wickets": 2,
                            },
                            {
                                "player_name": "Pranav Iyer",
                                "overs": 4.0,
                                "maidens": 0,
                                "runs": 31,
                                "wickets": 1,
                            },
                            {
                                "player_name": "Kabir Mehta",
                                "overs": 4.0,
                                "maidens": 0,
                                "runs": 26,
                                "wickets": 1,
                            },
                            {
                                "player_name": "Tyler Young",
                                "overs": 4.0,
                                "maidens": 0,
                                "runs": 38,
                                "wickets": 0,
                            },
                            {
                                "player_name": "Isaac Turner",
                                "overs": 4.0,
                                "maidens": 0,
                                "runs": 40,
                                "wickets": 0,
                            },
                        ],
                    },
                    {
                        "batting_team": "Perth Panthers",
                        "bowling_team": "Fremantle Falcons",
                        "runs": 164,
                        "wickets": 5,
                        "overs": 18.4,
                        "batting": [
                            {
                                "player_name": "Isaac Turner",
                                "runs": 58,
                                "balls": 40,
                                "fours": 7,
                                "sixes": 1,
                                "dismissal": "c Walker b Ross",
                                "is_not_out": False,
                            },
                            {
                                "player_name": "Joel Francis",
                                "runs": 23,
                                "balls": 19,
                                "fours": 2,
                                "sixes": 0,
                                "dismissal": "b Price",
                                "is_not_out": False,
                            },
                            {
                                "player_name": "Kabir Mehta",
                                "runs": 31,
                                "balls": 24,
                                "fours": 2,
                                "sixes": 1,
                                "dismissal": "c Reed b Das",
                                "is_not_out": False,
                            },
                            {
                                "player_name": "Tyler Young",
                                "runs": 17,
                                "balls": 13,
                                "fours": 1,
                                "sixes": 0,
                                "dismissal": "run out",
                                "is_not_out": False,
                            },
                            {
                                "player_name": "Pranav Iyer",
                                "runs": 22,
                                "balls": 12,
                                "fours": 2,
                                "sixes": 1,
                                "dismissal": "not out",
                                "is_not_out": True,
                            },
                            {
                                "player_name": "Hamish Cole",
                                "runs": 6,
                                "balls": 4,
                                "fours": 1,
                                "sixes": 0,
                                "dismissal": "not out",
                                "is_not_out": True,
                            },
                        ],
                        "bowling": [
                            {
                                "player_name": "Aiden Ross",
                                "overs": 4.0,
                                "maidens": 0,
                                "runs": 33,
                                "wickets": 1,
                            },
                            {
                                "player_name": "Callum Price",
                                "overs": 4.0,
                                "maidens": 0,
                                "runs": 29,
                                "wickets": 1,
                            },
                            {
                                "player_name": "Vikram Das",
                                "overs": 3.4,
                                "maidens": 0,
                                "runs": 34,
                                "wickets": 1,
                            },
                            {
                                "player_name": "Mason Reed",
                                "overs": 3.0,
                                "maidens": 0,
                                "runs": 26,
                                "wickets": 0,
                            },
                            {
                                "player_name": "Zane Brooks",
                                "overs": 4.0,
                                "maidens": 0,
                                "runs": 37,
                                "wickets": 0,
                            },
                        ],
                    },
                ],
            },
            {
                "key": "uwa-match-504",
                "team_a": "Crawley Crusaders",
                "team_b": "Claremont Comets",
                "scheduled_at": datetime(2026, 4, 21, 18, 30),
                "status": MatchStatus.LIVE,
                "toss_winner": "Claremont Comets",
                "toss_decision": TossDecision.BOWL,
                "innings": [
                    {
                        "batting_team": "Crawley Crusaders",
                        "bowling_team": "Claremont Comets",
                        "runs": 94,
                        "wickets": 2,
                        "overs": 12.1,
                        "batting": [
                            {
                                "player_name": "Aarav Patel",
                                "runs": 34,
                                "balls": 26,
                                "fours": 4,
                                "sixes": 0,
                                "dismissal": "c Mercer b Hart",
                                "is_not_out": False,
                            },
                            {
                                "player_name": "James Butler",
                                "runs": 21,
                                "balls": 17,
                                "fours": 2,
                                "sixes": 1,
                                "dismissal": "b Ali",
                                "is_not_out": False,
                            },
                            {
                                "player_name": "Ethan Wu",
                                "runs": 18,
                                "balls": 15,
                                "fours": 2,
                                "sixes": 0,
                                "dismissal": "not out",
                                "is_not_out": True,
                            },
                            {
                                "player_name": "Noah Smith",
                                "runs": 15,
                                "balls": 10,
                                "fours": 1,
                                "sixes": 1,
                                "dismissal": "not out",
                                "is_not_out": True,
                            },
                        ],
                        "bowling": [
                            {
                                "player_name": "Toby Hart",
                                "overs": 3.0,
                                "maidens": 0,
                                "runs": 18,
                                "wickets": 1,
                            },
                            {
                                "player_name": "Zaid Ali",
                                "overs": 3.0,
                                "maidens": 0,
                                "runs": 22,
                                "wickets": 1,
                            },
                            {
                                "player_name": "Kieran Moss",
                                "overs": 2.1,
                                "maidens": 0,
                                "runs": 16,
                                "wickets": 0,
                            },
                            {
                                "player_name": "Oliver Green",
                                "overs": 2.0,
                                "maidens": 0,
                                "runs": 20,
                                "wickets": 0,
                            },
                            {
                                "player_name": "Ryan D'Souza",
                                "overs": 2.0,
                                "maidens": 0,
                                "runs": 18,
                                "wickets": 0,
                            },
                        ],
                    }
                ],
            },
            {
                "key": "uwa-match-505",
                "team_a": "Perth Panthers",
                "team_b": "Fremantle Falcons",
                "scheduled_at": datetime(2026, 4, 19, 14, 0),
                "status": MatchStatus.UPCOMING,
            },
            {
                "key": "uwa-match-506",
                "team_a": "Nedlands Knights",
                "team_b": "Shenton Sharks",
                "scheduled_at": datetime(2026, 4, 26, 14, 0),
                "status": MatchStatus.UPCOMING,
            },
            {
                "key": "uwa-match-507",
                "team_a": "Crawley Crusaders",
                "team_b": "Fremantle Falcons",
                "scheduled_at": datetime(2026, 5, 3, 10, 0),
                "status": MatchStatus.UPCOMING,
            },
        ],
    },
    {
        "key": "perth_autumn_knockout",
        "name": "Perth Autumn Knockout",
        "description": "Straight knockout weekend for Perth suburban clubs.",
        "format": TournamentFormat.KNOCKOUT,
        "status": TournamentStatus.UPCOMING,
        "start_date": date(2026, 5, 2),
        "team_count": 8,
        "venue_key": "midland",
        "teams": [
            {
                "name": "Perth Pulse",
                "played": 0,
                "won": 0,
                "lost": 0,
                "points": 0,
                "nrr": 0.0,
            },
            {
                "name": "Midland Mavericks",
                "played": 0,
                "won": 0,
                "lost": 0,
                "points": 0,
                "nrr": 0.0,
            },
            {
                "name": "Joondalup Jets",
                "played": 0,
                "won": 0,
                "lost": 0,
                "points": 0,
                "nrr": 0.0,
            },
            {
                "name": "Victoria Park Vipers",
                "played": 0,
                "won": 0,
                "lost": 0,
                "points": 0,
                "nrr": 0.0,
            },
            {
                "name": "Bayswater Blaze",
                "played": 0,
                "won": 0,
                "lost": 0,
                "points": 0,
                "nrr": 0.0,
            },
            {
                "name": "South Perth Stallions",
                "played": 0,
                "won": 0,
                "lost": 0,
                "points": 0,
                "nrr": 0.0,
            },
            {
                "name": "Mount Lawley Lions",
                "played": 0,
                "won": 0,
                "lost": 0,
                "points": 0,
                "nrr": 0.0,
            },
            {
                "name": "Wanneroo Wolves",
                "played": 0,
                "won": 0,
                "lost": 0,
                "points": 0,
                "nrr": 0.0,
            },
        ],
        "matches": [
            {
                "team_a": "Perth Pulse",
                "team_b": "Midland Mavericks",
                "scheduled_at": datetime(2026, 5, 2, 9, 30),
                "status": MatchStatus.UPCOMING,
            },
            {
                "team_a": "Joondalup Jets",
                "team_b": "Victoria Park Vipers",
                "scheduled_at": datetime(2026, 5, 2, 12, 30),
                "status": MatchStatus.UPCOMING,
            },
            {
                "team_a": "Bayswater Blaze",
                "team_b": "South Perth Stallions",
                "scheduled_at": datetime(2026, 5, 2, 15, 30),
                "status": MatchStatus.UPCOMING,
            },
            {
                "team_a": "Mount Lawley Lions",
                "team_b": "Wanneroo Wolves",
                "scheduled_at": datetime(2026, 5, 2, 18, 30),
                "status": MatchStatus.UPCOMING,
            },
        ],
    },
    {
        "key": "fremantle_t20_cup",
        "name": "Fremantle T20 Cup",
        "description": "Harbour-side T20 carnival featuring clubs from across the south-west.",
        "format": TournamentFormat.GROUP_STAGE,
        "status": TournamentStatus.COMPLETED,
        "start_date": date(2025, 11, 10),
        "team_count": 12,
        "venue_key": "fremantle",
        "teams": [
            {
                "name": "South Beach Sailors",
                "played": 5,
                "won": 4,
                "lost": 1,
                "points": 8,
                "nrr": 1.42,
            },
            {
                "name": "Cockburn Chargers",
                "played": 5,
                "won": 4,
                "lost": 1,
                "points": 8,
                "nrr": 1.08,
            },
            {
                "name": "Melville Mariners",
                "played": 5,
                "won": 3,
                "lost": 2,
                "points": 6,
                "nrr": 0.76,
            },
            {
                "name": "Rockingham Raiders",
                "played": 5,
                "won": 3,
                "lost": 2,
                "points": 6,
                "nrr": 0.43,
            },
            {
                "name": "Kwinana Kings",
                "played": 5,
                "won": 3,
                "lost": 2,
                "points": 6,
                "nrr": 0.12,
            },
            {
                "name": "Mandurah Mavericks",
                "played": 5,
                "won": 2,
                "lost": 3,
                "points": 4,
                "nrr": -0.05,
            },
            {
                "name": "Fremantle Dock XI",
                "played": 5,
                "won": 2,
                "lost": 3,
                "points": 4,
                "nrr": -0.31,
            },
            {
                "name": "Bibra Lake Bashers",
                "played": 5,
                "won": 2,
                "lost": 3,
                "points": 4,
                "nrr": -0.48,
            },
            {
                "name": "Hilton Heat",
                "played": 5,
                "won": 1,
                "lost": 4,
                "points": 2,
                "nrr": -0.82,
            },
            {
                "name": "East Freo Fire",
                "played": 5,
                "won": 1,
                "lost": 4,
                "points": 2,
                "nrr": -1.11,
            },
            {
                "name": "Attadale Anchors",
                "played": 5,
                "won": 0,
                "lost": 5,
                "points": 0,
                "nrr": -1.52,
            },
            {
                "name": "Coogee Cobras",
                "played": 5,
                "won": 0,
                "lost": 5,
                "points": 0,
                "nrr": -1.96,
            },
        ],
        "matches": [
            {
                "team_a": "South Beach Sailors",
                "team_b": "Cockburn Chargers",
                "scheduled_at": datetime(2025, 11, 10, 10, 0),
                "status": MatchStatus.COMPLETED,
                "winner": "South Beach Sailors",
                "result_text": "South Beach Sailors won by 12 runs",
                "innings": [
                    {
                        "batting_team": "South Beach Sailors",
                        "bowling_team": "Cockburn Chargers",
                        "runs": 171,
                        "wickets": 6,
                        "overs": 20.0,
                    },
                    {
                        "batting_team": "Cockburn Chargers",
                        "bowling_team": "South Beach Sailors",
                        "runs": 159,
                        "wickets": 8,
                        "overs": 20.0,
                    },
                ],
            },
            {
                "team_a": "Melville Mariners",
                "team_b": "Rockingham Raiders",
                "scheduled_at": datetime(2025, 11, 11, 13, 30),
                "status": MatchStatus.COMPLETED,
                "winner": "Melville Mariners",
                "result_text": "Melville Mariners won by 4 wickets",
                "innings": [
                    {
                        "batting_team": "Rockingham Raiders",
                        "bowling_team": "Melville Mariners",
                        "runs": 148,
                        "wickets": 9,
                        "overs": 20.0,
                    },
                    {
                        "batting_team": "Melville Mariners",
                        "bowling_team": "Rockingham Raiders",
                        "runs": 149,
                        "wickets": 6,
                        "overs": 19.1,
                    },
                ],
            },
            {
                "team_a": "Kwinana Kings",
                "team_b": "Mandurah Mavericks",
                "scheduled_at": datetime(2025, 11, 12, 16, 0),
                "status": MatchStatus.COMPLETED,
                "winner": "Kwinana Kings",
                "result_text": "Kwinana Kings won by 21 runs",
                "innings": [
                    {
                        "batting_team": "Kwinana Kings",
                        "bowling_team": "Mandurah Mavericks",
                        "runs": 166,
                        "wickets": 7,
                        "overs": 20.0,
                    },
                    {
                        "batting_team": "Mandurah Mavericks",
                        "bowling_team": "Kwinana Kings",
                        "runs": 145,
                        "wickets": 9,
                        "overs": 20.0,
                    },
                ],
            },
            {
                "team_a": "Fremantle Dock XI",
                "team_b": "Bibra Lake Bashers",
                "scheduled_at": datetime(2025, 11, 13, 18, 30),
                "status": MatchStatus.COMPLETED,
                "winner": "Bibra Lake Bashers",
                "result_text": "Bibra Lake Bashers won by 3 wickets",
                "innings": [
                    {
                        "batting_team": "Fremantle Dock XI",
                        "bowling_team": "Bibra Lake Bashers",
                        "runs": 138,
                        "wickets": 8,
                        "overs": 20.0,
                    },
                    {
                        "batting_team": "Bibra Lake Bashers",
                        "bowling_team": "Fremantle Dock XI",
                        "runs": 141,
                        "wickets": 7,
                        "overs": 19.4,
                    },
                ],
            },
            {
                "team_a": "Hilton Heat",
                "team_b": "East Freo Fire",
                "scheduled_at": datetime(2025, 11, 14, 14, 0),
                "status": MatchStatus.COMPLETED,
                "winner": "Hilton Heat",
                "result_text": "Hilton Heat won by 8 wickets",
                "innings": [
                    {
                        "batting_team": "East Freo Fire",
                        "bowling_team": "Hilton Heat",
                        "runs": 121,
                        "wickets": 10,
                        "overs": 18.5,
                    },
                    {
                        "batting_team": "Hilton Heat",
                        "bowling_team": "East Freo Fire",
                        "runs": 122,
                        "wickets": 2,
                        "overs": 14.2,
                    },
                ],
            },
        ],
    },
    {
        "key": "cottesloe_beach_sixes",
        "name": "Cottesloe Beach Sixes",
        "description": "A short-format beach cricket event played across one sunny Saturday.",
        "format": TournamentFormat.ROUND_ROBIN,
        "status": TournamentStatus.UPCOMING,
        "start_date": date(2026, 6, 20),
        "team_count": 4,
        "venue_key": "cottesloe",
        "teams": [
            {
                "name": "Cottesloe Chargers",
                "played": 0,
                "won": 0,
                "lost": 0,
                "points": 0,
                "nrr": 0.0,
            },
            {
                "name": "Scarborough Surfers",
                "played": 0,
                "won": 0,
                "lost": 0,
                "points": 0,
                "nrr": 0.0,
            },
            {
                "name": "City Beach Breakers",
                "played": 0,
                "won": 0,
                "lost": 0,
                "points": 0,
                "nrr": 0.0,
            },
            {
                "name": "Trigg Turtles",
                "played": 0,
                "won": 0,
                "lost": 0,
                "points": 0,
                "nrr": 0.0,
            },
        ],
        "matches": [
            {
                "team_a": "Cottesloe Chargers",
                "team_b": "Scarborough Surfers",
                "scheduled_at": datetime(2026, 6, 20, 9, 0),
                "status": MatchStatus.UPCOMING,
            },
            {
                "team_a": "City Beach Breakers",
                "team_b": "Trigg Turtles",
                "scheduled_at": datetime(2026, 6, 20, 10, 15),
                "status": MatchStatus.UPCOMING,
            },
            {
                "team_a": "Cottesloe Chargers",
                "team_b": "City Beach Breakers",
                "scheduled_at": datetime(2026, 6, 20, 12, 0),
                "status": MatchStatus.UPCOMING,
            },
            {
                "team_a": "Scarborough Surfers",
                "team_b": "Trigg Turtles",
                "scheduled_at": datetime(2026, 6, 20, 13, 15),
                "status": MatchStatus.UPCOMING,
            },
        ],
    },
    {
        "key": "nedlands_invitational",
        "name": "Nedlands Invitational",
        "description": "Invitation-only knockout featuring leading metro cricket clubs.",
        "format": TournamentFormat.KNOCKOUT,
        "status": TournamentStatus.COMPLETED,
        "start_date": date(2025, 9, 1),
        "team_count": 8,
        "venue_key": "nedlands",
        "teams": [
            {
                "name": "University Aces",
                "played": 3,
                "won": 3,
                "lost": 0,
                "points": 6,
                "nrr": 1.67,
            },
            {
                "name": "Subiaco Strikers",
                "played": 2,
                "won": 2,
                "lost": 1,
                "points": 4,
                "nrr": 0.92,
            },
            {
                "name": "Nedlands Navigators",
                "played": 1,
                "won": 1,
                "lost": 1,
                "points": 2,
                "nrr": 0.21,
            },
            {
                "name": "Mount Claremont Kings",
                "played": 1,
                "won": 1,
                "lost": 1,
                "points": 2,
                "nrr": 0.11,
            },
            {
                "name": "Wembley Warriors",
                "played": 1,
                "won": 0,
                "lost": 1,
                "points": 0,
                "nrr": -0.18,
            },
            {
                "name": "Leederville Lightning",
                "played": 1,
                "won": 0,
                "lost": 1,
                "points": 0,
                "nrr": -0.42,
            },
            {
                "name": "Floreat Falcons",
                "played": 1,
                "won": 0,
                "lost": 1,
                "points": 0,
                "nrr": -0.73,
            },
            {
                "name": "Dalkeith Dolphins",
                "played": 1,
                "won": 0,
                "lost": 1,
                "points": 0,
                "nrr": -1.04,
            },
        ],
        "matches": [
            {
                "team_a": "University Aces",
                "team_b": "Dalkeith Dolphins",
                "scheduled_at": datetime(2025, 9, 1, 9, 0),
                "status": MatchStatus.COMPLETED,
                "winner": "University Aces",
                "result_text": "University Aces won by 38 runs",
                "innings": [
                    {
                        "batting_team": "University Aces",
                        "bowling_team": "Dalkeith Dolphins",
                        "runs": 154,
                        "wickets": 6,
                        "overs": 20.0,
                    },
                    {
                        "batting_team": "Dalkeith Dolphins",
                        "bowling_team": "University Aces",
                        "runs": 116,
                        "wickets": 10,
                        "overs": 18.3,
                    },
                ],
            },
            {
                "team_a": "Subiaco Strikers",
                "team_b": "Floreat Falcons",
                "scheduled_at": datetime(2025, 9, 1, 12, 0),
                "status": MatchStatus.COMPLETED,
                "winner": "Subiaco Strikers",
                "result_text": "Subiaco Strikers won by 5 wickets",
                "innings": [
                    {
                        "batting_team": "Floreat Falcons",
                        "bowling_team": "Subiaco Strikers",
                        "runs": 139,
                        "wickets": 8,
                        "overs": 20.0,
                    },
                    {
                        "batting_team": "Subiaco Strikers",
                        "bowling_team": "Floreat Falcons",
                        "runs": 140,
                        "wickets": 5,
                        "overs": 18.4,
                    },
                ],
            },
            {
                "team_a": "Nedlands Navigators",
                "team_b": "Leederville Lightning",
                "scheduled_at": datetime(2025, 9, 1, 15, 0),
                "status": MatchStatus.COMPLETED,
                "winner": "Nedlands Navigators",
                "result_text": "Nedlands Navigators won by 2 wickets",
                "innings": [
                    {
                        "batting_team": "Leederville Lightning",
                        "bowling_team": "Nedlands Navigators",
                        "runs": 128,
                        "wickets": 9,
                        "overs": 20.0,
                    },
                    {
                        "batting_team": "Nedlands Navigators",
                        "bowling_team": "Leederville Lightning",
                        "runs": 129,
                        "wickets": 8,
                        "overs": 19.5,
                    },
                ],
            },
            {
                "team_a": "Mount Claremont Kings",
                "team_b": "Wembley Warriors",
                "scheduled_at": datetime(2025, 9, 1, 18, 0),
                "status": MatchStatus.COMPLETED,
                "winner": "Mount Claremont Kings",
                "result_text": "Mount Claremont Kings won by 16 runs",
                "innings": [
                    {
                        "batting_team": "Mount Claremont Kings",
                        "bowling_team": "Wembley Warriors",
                        "runs": 146,
                        "wickets": 7,
                        "overs": 20.0,
                    },
                    {
                        "batting_team": "Wembley Warriors",
                        "bowling_team": "Mount Claremont Kings",
                        "runs": 130,
                        "wickets": 9,
                        "overs": 20.0,
                    },
                ],
            },
            {
                "team_a": "University Aces",
                "team_b": "Mount Claremont Kings",
                "scheduled_at": datetime(2025, 9, 6, 13, 0),
                "status": MatchStatus.COMPLETED,
                "winner": "University Aces",
                "result_text": "University Aces won by 7 wickets",
                "innings": [
                    {
                        "batting_team": "Mount Claremont Kings",
                        "bowling_team": "University Aces",
                        "runs": 133,
                        "wickets": 10,
                        "overs": 19.2,
                    },
                    {
                        "batting_team": "University Aces",
                        "bowling_team": "Mount Claremont Kings",
                        "runs": 134,
                        "wickets": 3,
                        "overs": 15.4,
                    },
                ],
            },
            {
                "team_a": "Subiaco Strikers",
                "team_b": "Nedlands Navigators",
                "scheduled_at": datetime(2025, 9, 6, 16, 30),
                "status": MatchStatus.COMPLETED,
                "winner": "Subiaco Strikers",
                "result_text": "Subiaco Strikers won by 11 runs",
                "innings": [
                    {
                        "batting_team": "Subiaco Strikers",
                        "bowling_team": "Nedlands Navigators",
                        "runs": 151,
                        "wickets": 6,
                        "overs": 20.0,
                    },
                    {
                        "batting_team": "Nedlands Navigators",
                        "bowling_team": "Subiaco Strikers",
                        "runs": 140,
                        "wickets": 8,
                        "overs": 20.0,
                    },
                ],
            },
            {
                "team_a": "University Aces",
                "team_b": "Subiaco Strikers",
                "scheduled_at": datetime(2025, 9, 13, 15, 0),
                "status": MatchStatus.COMPLETED,
                "winner": "University Aces",
                "result_text": "University Aces won by 4 wickets",
                "innings": [
                    {
                        "batting_team": "Subiaco Strikers",
                        "bowling_team": "University Aces",
                        "runs": 160,
                        "wickets": 7,
                        "overs": 20.0,
                    },
                    {
                        "batting_team": "University Aces",
                        "bowling_team": "Subiaco Strikers",
                        "runs": 161,
                        "wickets": 6,
                        "overs": 19.3,
                    },
                ],
            },
        ],
    },
    {
        "key": "swan_valley_shield",
        "name": "Swan Valley Shield",
        "description": "Regional T20 shield with pools feeding into a finals series.",
        "format": TournamentFormat.GROUP_STAGE,
        "status": TournamentStatus.LIVE,
        "start_date": date(2026, 2, 1),
        "team_count": 10,
        "venue_key": "swan_valley",
        "teams": [
            {
                "name": "Guildford Giants",
                "played": 4,
                "won": 3,
                "lost": 1,
                "points": 6,
                "nrr": 1.12,
            },
            {
                "name": "Caversham Centurions",
                "played": 4,
                "won": 3,
                "lost": 1,
                "points": 6,
                "nrr": 0.98,
            },
            {
                "name": "Bullsbrook Blasters",
                "played": 4,
                "won": 2,
                "lost": 2,
                "points": 4,
                "nrr": 0.41,
            },
            {
                "name": "Ellenbrook Eagles",
                "played": 4,
                "won": 2,
                "lost": 2,
                "points": 4,
                "nrr": 0.15,
            },
            {
                "name": "Midvale Meteors",
                "played": 4,
                "won": 2,
                "lost": 2,
                "points": 4,
                "nrr": -0.08,
            },
            {
                "name": "Swan View Sixers",
                "played": 4,
                "won": 2,
                "lost": 2,
                "points": 4,
                "nrr": -0.16,
            },
            {
                "name": "Helena Valley Hawks",
                "played": 4,
                "won": 1,
                "lost": 3,
                "points": 2,
                "nrr": -0.46,
            },
            {
                "name": "Bassendean Bruisers",
                "played": 4,
                "won": 1,
                "lost": 3,
                "points": 2,
                "nrr": -0.77,
            },
            {
                "name": "Jane Brook Jaguars",
                "played": 4,
                "won": 1,
                "lost": 3,
                "points": 2,
                "nrr": -1.02,
            },
            {
                "name": "Herne Hill Heat",
                "played": 4,
                "won": 1,
                "lost": 3,
                "points": 2,
                "nrr": -1.17,
            },
        ],
        "matches": [
            {
                "team_a": "Guildford Giants",
                "team_b": "Bassendean Bruisers",
                "scheduled_at": datetime(2026, 2, 14, 11, 0),
                "status": MatchStatus.COMPLETED,
                "winner": "Guildford Giants",
                "result_text": "Guildford Giants won by 27 runs",
                "innings": [
                    {
                        "batting_team": "Guildford Giants",
                        "bowling_team": "Bassendean Bruisers",
                        "runs": 169,
                        "wickets": 6,
                        "overs": 20.0,
                    },
                    {
                        "batting_team": "Bassendean Bruisers",
                        "bowling_team": "Guildford Giants",
                        "runs": 142,
                        "wickets": 9,
                        "overs": 20.0,
                    },
                ],
            },
            {
                "team_a": "Caversham Centurions",
                "team_b": "Jane Brook Jaguars",
                "scheduled_at": datetime(2026, 2, 21, 11, 0),
                "status": MatchStatus.COMPLETED,
                "winner": "Caversham Centurions",
                "result_text": "Caversham Centurions won by 8 wickets",
                "innings": [
                    {
                        "batting_team": "Jane Brook Jaguars",
                        "bowling_team": "Caversham Centurions",
                        "runs": 126,
                        "wickets": 10,
                        "overs": 19.1,
                    },
                    {
                        "batting_team": "Caversham Centurions",
                        "bowling_team": "Jane Brook Jaguars",
                        "runs": 127,
                        "wickets": 2,
                        "overs": 15.0,
                    },
                ],
            },
            {
                "team_a": "Bullsbrook Blasters",
                "team_b": "Ellenbrook Eagles",
                "scheduled_at": datetime(2026, 3, 7, 14, 30),
                "status": MatchStatus.LIVE,
                "toss_winner": "Ellenbrook Eagles",
                "toss_decision": TossDecision.BOWL,
                "innings": [
                    {
                        "batting_team": "Bullsbrook Blasters",
                        "bowling_team": "Ellenbrook Eagles",
                        "runs": 87,
                        "wickets": 3,
                        "overs": 11.4,
                    }
                ],
            },
            {
                "team_a": "Midvale Meteors",
                "team_b": "Swan View Sixers",
                "scheduled_at": datetime(2026, 3, 14, 10, 30),
                "status": MatchStatus.UPCOMING,
            },
            {
                "team_a": "Helena Valley Hawks",
                "team_b": "Herne Hill Heat",
                "scheduled_at": datetime(2026, 3, 14, 14, 30),
                "status": MatchStatus.UPCOMING,
            },
        ],
    },
]

SEED_COMMENTS = [
    {
        "match_key": "uwa-match-501",
        "user_key": "cheng",
        "body": "Great hitting from Aarav today — 78 off 52 set the tone.",
        "created_at": datetime(2026, 4, 12, 12, 5, tzinfo=UTC),
    },
    {
        "match_key": "uwa-match-501",
        "user_key": "priya",
        "body": "Knights really needed one more partnership in the middle overs.",
        "created_at": datetime(2026, 4, 12, 12, 22, tzinfo=UTC),
    },
    {
        "match_key": "uwa-match-501",
        "user_key": "daniel",
        "body": "Pitch was drying out by the second innings — tough to chase 183.",
        "created_at": datetime(2026, 4, 13, 0, 41, tzinfo=UTC),
    },
]
