/* Mock data for the Cricket Tournament Management System frontend.
   In the real application this will be replaced by AJAX calls to the
   Flask backend. */

window.CTM_MOCK = {
  /* Role is driven by js/roles.js — defaults to 'organizer' for demo.
     Two demo personas below so the role switcher can flip between them
     without losing avatar/name continuity. */
  currentUser: {
    id: 1,
    displayName: 'Cheng Zhang',
    initials: 'CZ',
    email: 'cheng@example.com',
    role: 'organizer',
    bio: 'Club cricketer from Perth. Organiser of the UWA Social League.',
  },

  demoUsers: {
    organizer: {
      id: 1,
      displayName: 'Cheng Zhang',
      initials: 'CZ',
      email: 'cheng@example.com',
      role: 'organizer',
      bio: 'Club cricketer from Perth. Organiser of the UWA Social League.',
    },
    user: {
      id: 2,
      displayName: 'Priya Menon',
      initials: 'PM',
      email: 'priya@example.com',
      role: 'user',
      bio: 'Fan of short-format cricket. Follows local WA leagues.',
    },
  },

  summary: {
    myTournaments: 3,
    upcomingMatches: 4,
    recentResults: 7,
    totalPlayers: 52,
  },

  tournaments: [
    {
      id: 101,
      name: 'UWA Social League 2026',
      format: 'Round Robin',
      status: 'live',
      teams: 6,
      startDate: '2026-03-15',
      organiser: 'Cheng Zhang',
      cover: '',
    },
    {
      id: 102,
      name: 'Perth Autumn Knockout',
      format: 'Knockout',
      status: 'upcoming',
      teams: 8,
      startDate: '2026-05-02',
      organiser: 'Leon Nel',
      cover: 'alt',
    },
    {
      id: 103,
      name: 'Fremantle T20 Cup',
      format: 'Group Stage',
      status: 'completed',
      teams: 12,
      startDate: '2025-11-10',
      organiser: 'Hafiz Zeeshan Ahmad',
      cover: 'warm',
    },
    {
      id: 104,
      name: 'Cottesloe Beach Sixes',
      format: 'Round Robin',
      status: 'upcoming',
      teams: 4,
      startDate: '2026-06-20',
      organiser: 'Cheng Zhang',
      cover: 'alt',
    },
    {
      id: 105,
      name: 'Nedlands Invitational',
      format: 'Knockout',
      status: 'completed',
      teams: 8,
      startDate: '2025-09-01',
      organiser: 'Leon Nel',
      cover: 'warm',
    },
    {
      id: 106,
      name: 'Swan Valley Shield',
      format: 'Group Stage',
      status: 'live',
      teams: 10,
      startDate: '2026-02-01',
      organiser: 'Hafiz Zeeshan Ahmad',
      cover: '',
    },
  ],

  tournament: {
    id: 101,
    name: 'UWA Social League 2026',
    format: 'Round Robin',
    status: 'live',
    startDate: '2026-03-15',
    organiser: 'Cheng Zhang',
    organiserId: 1,
    description: 'Friendly weekly 20-over matches between UWA clubs.',
    venue: {
      name: 'UWA Sports Park',
      address: 'Hackett Dr, Crawley WA 6009, Australia',
      lat: -31.9833,
      lng: 115.8167,
    },
    standings: [
      {
        rank: 1,
        team: 'Crawley Crusaders',
        played: 5,
        won: 5,
        lost: 0,
        points: 10,
        nrr: '+2.15',
      },
      {
        rank: 2,
        team: 'Nedlands Knights',
        played: 5,
        won: 3,
        lost: 2,
        points: 6,
        nrr: '+0.82',
      },
      {
        rank: 3,
        team: 'Claremont Comets',
        played: 5,
        won: 3,
        lost: 2,
        points: 6,
        nrr: '+0.41',
      },
      {
        rank: 4,
        team: 'Shenton Sharks',
        played: 5,
        won: 2,
        lost: 3,
        points: 4,
        nrr: '-0.30',
      },
      {
        rank: 5,
        team: 'Fremantle Falcons',
        played: 5,
        won: 1,
        lost: 4,
        points: 2,
        nrr: '-1.25',
      },
      {
        rank: 6,
        team: 'Perth Panthers',
        played: 5,
        won: 1,
        lost: 4,
        points: 2,
        nrr: '-1.84',
      },
    ],
    fixtures: [
      {
        id: 501,
        date: '2026-04-12',
        time: '14:00',
        teamA: 'Crawley Crusaders',
        teamB: 'Nedlands Knights',
        scoreA: '182/6',
        scoreB: '165/9',
        overs: '20.0',
        status: 'completed',
        result: 'Crusaders won by 17 runs',
      },
      {
        id: 502,
        date: '2026-04-14',
        time: '18:30',
        teamA: 'Claremont Comets',
        teamB: 'Shenton Sharks',
        scoreA: '145/7',
        scoreB: '147/4',
        overs: '19.2',
        status: 'completed',
        result: 'Sharks won by 6 wickets',
      },
      {
        id: 503,
        date: '2026-04-19',
        time: '14:00',
        teamA: 'Perth Panthers',
        teamB: 'Fremantle Falcons',
        status: 'upcoming',
      },
      {
        id: 504,
        date: '2026-04-21',
        time: '18:30',
        teamA: 'Crawley Crusaders',
        teamB: 'Claremont Comets',
        status: 'live',
        scoreA: '94/2 (12.1)',
      },
      {
        id: 505,
        date: '2026-04-26',
        time: '14:00',
        teamA: 'Nedlands Knights',
        teamB: 'Shenton Sharks',
        status: 'upcoming',
      },
    ],
    topPerformers: {
      batting: [
        {
          rank: 1,
          player: 'Aarav Patel',
          team: 'Crawley Crusaders',
          runs: 287,
          avg: 71.75,
          sr: 142.8,
        },
        {
          rank: 2,
          player: "Liam O'Connor",
          team: 'Nedlands Knights',
          runs: 241,
          avg: 60.25,
          sr: 131.2,
        },
        {
          rank: 3,
          player: 'Rohan Das',
          team: 'Claremont Comets',
          runs: 198,
          avg: 49.5,
          sr: 125.6,
        },
      ],
      bowling: [
        {
          rank: 1,
          player: 'Imran Khan',
          team: 'Shenton Sharks',
          wickets: 12,
          avg: 14.2,
          econ: 6.1,
        },
        {
          rank: 2,
          player: 'James Butler',
          team: 'Crawley Crusaders',
          wickets: 10,
          avg: 16.8,
          econ: 6.8,
        },
        {
          rank: 3,
          player: 'Sachin Rao',
          team: 'Nedlands Knights',
          wickets: 9,
          avg: 18.3,
          econ: 7.2,
        },
      ],
    },
  },

  match: {
    id: 501,
    tournamentId: 101,
    tournamentName: 'UWA Social League 2026',
    date: '2026-04-12',
    venue: {
      name: 'UWA Sports Park, Oval 3',
      address: 'Hackett Dr, Crawley WA 6009, Australia',
      lat: -31.9833,
      lng: 115.8167,
    },
    toss: 'Crawley Crusaders won the toss and elected to bat',
    result: 'Crawley Crusaders won by 17 runs',
    teamA: {
      name: 'Crawley Crusaders',
      short: 'CRU',
      score: '182/6',
      overs: '20.0',
    },
    teamB: {
      name: 'Nedlands Knights',
      short: 'NED',
      score: '165/9',
      overs: '20.0',
    },
    innings: [
      {
        team: 'Crawley Crusaders innings — 182/6 (20.0)',
        batting: [
          {
            player: 'Aarav Patel',
            how: 'c Rao b Khan',
            runs: 78,
            balls: 52,
            fours: 8,
            sixes: 3,
            sr: 150.0,
          },
          {
            player: 'James Butler',
            how: 'b Khan',
            runs: 45,
            balls: 38,
            fours: 5,
            sixes: 1,
            sr: 118.4,
          },
          {
            player: 'Ethan Wu',
            how: 'run out',
            runs: 22,
            balls: 18,
            fours: 2,
            sixes: 0,
            sr: 122.2,
          },
          {
            player: 'Noah Smith',
            how: 'c & b Singh',
            runs: 14,
            balls: 9,
            fours: 1,
            sixes: 1,
            sr: 155.6,
          },
          {
            player: 'Jacob Lim',
            how: 'not out',
            runs: 12,
            balls: 8,
            fours: 1,
            sixes: 0,
            sr: 150.0,
          },
          {
            player: 'Arjun Rao',
            how: 'b Khan',
            runs: 4,
            balls: 5,
            fours: 0,
            sixes: 0,
            sr: 80.0,
          },
          {
            player: 'Daniel Park',
            how: 'not out',
            runs: 2,
            balls: 2,
            fours: 0,
            sixes: 0,
            sr: 100.0,
          },
        ],
        bowling: [
          {
            player: 'Imran Khan',
            overs: '4.0',
            maidens: 0,
            runs: 28,
            wickets: 3,
            econ: 7.0,
          },
          {
            player: 'Ravi Singh',
            overs: '4.0',
            maidens: 0,
            runs: 34,
            wickets: 1,
            econ: 8.5,
          },
          {
            player: 'Sachin Rao',
            overs: '4.0',
            maidens: 0,
            runs: 41,
            wickets: 0,
            econ: 10.3,
          },
          {
            player: 'Ben Cooper',
            overs: '4.0',
            maidens: 0,
            runs: 39,
            wickets: 1,
            econ: 9.8,
          },
          {
            player: 'Matt Hayes',
            overs: '4.0',
            maidens: 0,
            runs: 40,
            wickets: 0,
            econ: 10.0,
          },
        ],
      },
      {
        team: 'Nedlands Knights innings — 165/9 (20.0)',
        batting: [
          {
            player: "Liam O'Connor",
            how: 'c Butler b Park',
            runs: 62,
            balls: 44,
            fours: 6,
            sixes: 2,
            sr: 140.9,
          },
          {
            player: 'Ravi Singh',
            how: 'b Lim',
            runs: 33,
            balls: 28,
            fours: 3,
            sixes: 1,
            sr: 117.9,
          },
          {
            player: 'Sachin Rao',
            how: 'c Wu b Butler',
            runs: 21,
            balls: 20,
            fours: 2,
            sixes: 0,
            sr: 105.0,
          },
          {
            player: 'Ben Cooper',
            how: 'lbw b Lim',
            runs: 18,
            balls: 14,
            fours: 1,
            sixes: 1,
            sr: 128.6,
          },
          {
            player: 'Matt Hayes',
            how: 'c Smith b Butler',
            runs: 10,
            balls: 11,
            fours: 1,
            sixes: 0,
            sr: 90.9,
          },
          {
            player: 'Imran Khan',
            how: 'not out',
            runs: 9,
            balls: 8,
            fours: 0,
            sixes: 0,
            sr: 112.5,
          },
        ],
        bowling: [
          {
            player: 'Daniel Park',
            overs: '4.0',
            maidens: 0,
            runs: 29,
            wickets: 2,
            econ: 7.3,
          },
          {
            player: 'Jacob Lim',
            overs: '4.0',
            maidens: 1,
            runs: 22,
            wickets: 3,
            econ: 5.5,
          },
          {
            player: 'James Butler',
            overs: '4.0',
            maidens: 0,
            runs: 34,
            wickets: 2,
            econ: 8.5,
          },
          {
            player: 'Arjun Rao',
            overs: '4.0',
            maidens: 0,
            runs: 38,
            wickets: 1,
            econ: 9.5,
          },
          {
            player: 'Noah Smith',
            overs: '4.0',
            maidens: 0,
            runs: 42,
            wickets: 1,
            econ: 10.5,
          },
        ],
      },
    ],
  },

  /* Seed comments for both tournament-detail.html and match-scorecard.html.
     `role` decides whether the organizer badge renders next to the author. */
  comments: [
    {
      id: 9001,
      matchId: 501,
      tournamentId: 101,
      authorId: 1,
      authorName: 'Cheng Zhang',
      initials: 'CZ',
      role: 'organizer',
      body: 'Great hitting from Aarav today — 78 off 52 set the tone. Player of the match was a clear call.',
      createdAt: '2026-04-12T20:05:00+08:00',
    },
    {
      id: 9002,
      matchId: 501,
      tournamentId: 101,
      authorId: 2,
      authorName: 'Priya Menon',
      initials: 'PM',
      role: 'user',
      body: 'Knights really needed one more partnership in the middle overs. Spin bowling from Lim was lethal.',
      createdAt: '2026-04-12T20:22:00+08:00',
    },
    {
      id: 9003,
      matchId: 501,
      tournamentId: 101,
      authorId: 7,
      authorName: 'Daniel Park',
      initials: 'DP',
      role: 'user',
      body: 'Pitch was drying out by the second innings — tough to chase 183.',
      createdAt: '2026-04-13T08:41:00+08:00',
    },
  ],

  /* Sample payload shaped like the CricketData.org /currentMatches response
     so the UI can be built and smoke-tested before the Flask proxy exists. */
  liveFeed: {
    status: 'success',
    data: [
      {
        id: 'crk-2026-ipl-34',
        name: 'Mumbai Indians vs Chennai Super Kings',
        status: 'Mumbai Indians need 42 runs in 36 balls',
        venue: 'Wankhede Stadium, Mumbai',
        matchType: 't20',
        teamInfo: [
          { name: 'Mumbai Indians', shortname: 'MI' },
          { name: 'Chennai Super Kings', shortname: 'CSK' },
        ],
        score: [
          { inning: 'Chennai Super Kings Innings', r: 178, w: 6, o: 20 },
          { inning: 'Mumbai Indians Innings', r: 137, w: 4, o: 14 },
        ],
      },
      {
        id: 'crk-2026-ipl-33',
        name: 'Royal Challengers Bengaluru vs Rajasthan Royals',
        status: 'Rajasthan Royals won by 5 wickets',
        venue: 'M. Chinnaswamy Stadium, Bengaluru',
        matchType: 't20',
        teamInfo: [
          { name: 'Royal Challengers Bengaluru', shortname: 'RCB' },
          { name: 'Rajasthan Royals', shortname: 'RR' },
        ],
        score: [
          {
            inning: 'Royal Challengers Bengaluru Innings',
            r: 164,
            w: 8,
            o: 20,
          },
          { inning: 'Rajasthan Royals Innings', r: 167, w: 5, o: 19.2 },
        ],
      },
    ],
  },

  player: {
    id: 9001,
    name: 'Aarav Patel',
    team: 'Crawley Crusaders',
    tournament: 'UWA Social League 2026',
    role: 'Top-order batter / Part-time off-spin',
    summary: {
      matches: 5,
      runs: 287,
      average: 71.75,
      strikeRate: 142.8,
      fifties: 2,
      hundreds: 1,
      wickets: 3,
      bowlingAvg: 22.3,
      economy: 7.4,
    },
    matches: [
      { match: 'vs Nedlands Knights', runs: 78, balls: 52, wkts: 1, overs: 2 },
      { match: 'vs Claremont Comets', runs: 104, balls: 66, wkts: 0, overs: 0 },
      { match: 'vs Shenton Sharks', runs: 42, balls: 30, wkts: 1, overs: 3 },
      { match: 'vs Fremantle Falcons', runs: 33, balls: 28, wkts: 0, overs: 0 },
      { match: 'vs Perth Panthers', runs: 30, balls: 20, wkts: 1, overs: 2 },
    ],
  },
};
